export const LOAD_IMAGE_DATA = 'LOAD_IMAGE_DATA';
export const LOAD_IMAGE_DATA_REQUEST = 'LOAD_IMAGE_DATA_REQUEST';
export const LOAD_IMAGE_DATA_SUCCESS = 'LOAD_IMAGE_DATA_SUCCESS';
export const LOAD_IMAGE_DATA_FAILURE = 'LOAD_IMAGE_DATA_FAILURE';